import { formatPages } from './format-pages'
import { taskGuides } from './task-guides'

export default function ImageToPdfGuide({ formatPage }: { formatPage?: typeof formatPages[number] }) {
  return <section className="pdf-guide" aria-labelledby="pdf-guide-title">
    <nav aria-label="Breadcrumb"><a href="/">Bloomollo</a><span aria-hidden="true"> / </span><span>{formatPage ? `${formatPage.label} to PDF` : 'Image to PDF'}</span></nav>
    {formatPage && <article><h2>{formatPage.heading}</h2><p>{formatPage.intro}</p><p>{formatPage.tip}</p><h3>{formatPage.question}</h3><p>{formatPage.answer}</p></article>}
    <header><p className="pdf-guide-kicker">FREE · LOCAL FILE PROCESSING</p><h2 id="pdf-guide-title">Convert images and JPG photos to PDF without uploading</h2><p>Combine assignment photos, scanned pages, receipts or screenshots into one PDF. Bloomollo converts your images in your browser: the converter does not send your image files to a server. No account, installation or watermark.</p><a href="#main-content">Go to the converter ↑</a></header>
    <div className="pdf-guide-columns">
      <article><h2>How to convert JPG to PDF</h2><ol><li><strong>Choose your images.</strong> Select JPG or JPEG photos, PNG screenshots, or other supported images from your device. You can also drop files into the converter on desktop.</li><li><strong>Set the page order.</strong> Drag previews to reorder them or use the arrow buttons. On mobile, briefly hold a preview before dragging. Rotate any sideways images.</li><li><strong>Choose your layout.</strong> Use A4, US Letter or Fit to image. Choose automatic, portrait or landscape orientation and optional margins. Margins default to None.</li><li><strong>Download your PDF.</strong> Select Download PDF once. The converter processes the images and starts the download when it finishes.</li></ol></article>
      <article><h2>Image formats, limits and quality</h2><p>Supported formats are JPG/JPEG, PNG, WebP, GIF, BMP and AVIF, subject to your browser’s decoding support. Mix supported formats in the same PDF. Each image becomes one page.</p><p>Convert up to 60 images per batch, with a maximum of 25 MB per image, 150 MB total and 40 megapixels per image. Larger batches may need more memory on a phone.</p><p>Balanced quality is the default. High retains more detail; Compact produces a smaller file. Images keep their proportions and are not cropped. Transparency becomes white. Output is compressed, so High is not lossless. Animated formats produce a still image, not an animated PDF.</p></article>
    </div>
    <section className="pdf-guide-faq" aria-labelledby="pdf-guide-faq-title"><h2 id="pdf-guide-faq-title">Image to PDF questions</h2>
      <details><summary>Is JPG to PDF conversion free?</summary><p>Yes. This converter is free to use without an account, installation or added watermark. The batch limits above still apply.</p></details>
      <details><summary>Can I combine multiple JPG and PNG images into one PDF?</summary><p>Yes. Select your supported images together, arrange their order and download one PDF. JPG and JPEG are two filename extensions for the same image format, and both are accepted.</p></details>
      <details><summary>Are my images uploaded or stored by Bloomollo?</summary><p>The converter processes image files locally in your browser and does not upload them to a conversion server. The website itself still makes normal requests for its code, fonts and other assets. See the <a href="/privacy/">privacy policy</a> for website data handling.</p></details>
      <details><summary>Can I convert photos to PDF on my phone?</summary><p>Use a modern browser that supports Web Workers, OffscreenCanvas and image decoding. Choose images from your phone, hold a preview briefly to reorder it, and use PDF settings to change the page layout. If a large batch fails, try fewer or smaller images.</p></details>
      <details><summary>Why does my PDF have space around the image?</summary><p>Margins default to None, but A4 and US Letter have fixed proportions. An image with a different shape may still leave white space because it is not cropped or stretched. Choose Fit to image for a page shaped to each image.</p></details>
      <details><summary>Does this converter make text searchable?</summary><p>No. It creates image-based PDF pages and does not perform OCR. Text photographed inside an image does not become selectable or searchable text.</p></details>
      <details><summary>Why is an image rejected or a download not starting?</summary><p>Check the file format and size limits, and try a smaller batch or an updated browser. Damaged files and formats your browser cannot decode may be rejected. Your browser controls where the generated PDF is saved and may show a download prompt.</p></details>
    </section>
    <nav aria-label="Image conversion formats"><h2>Choose an image format</h2><p><a href="/tools/image-to-pdf/">All images to PDF</a>{formatPages.map(page => <span key={page.slug}> · <a href={`/tools/${page.slug}/`} aria-current={formatPage?.slug === page.slug ? 'page' : undefined}>{page.label} to PDF</a></span>)}</p></nav>
    <nav aria-label="PDF task guides"><h2>Practical PDF guides</h2>{taskGuides.map(guide => <p key={guide.slug}><a href={`/guides/${guide.slug}/`}>{guide.title}</a></p>)}</nav>
  </section>
}