import { translator, localeMetadata } from './locales'
import type { Locale } from './locales'

const guides = {
  hi: ['चित्रों से PDF कैसे बनाएँ', 'अपने JPG, PNG, WebP, GIF, BMP या AVIF चित्र चुनें। क्रम बदलने के लिए मोबाइल पर चित्र को कुछ देर दबाकर खींचें। तीर वाले बटन भी उपलब्ध हैं।', 'A4, US Letter या चित्र के अनुसार पृष्ठ आकार चुनें। मार्जिन शुरू में नहीं होते। Download PDF बटन दबाने पर फ़ाइल तैयार होती है और डाउनलोड शुरू होता है।', 'सीमाएँ और गुणवत्ता', 'एक बार में 60 चित्र, प्रति चित्र 25 MB, कुल 150 MB और प्रति चित्र 40 मेगापिक्सेल तक। ब्राउज़र को चित्र प्रारूप पढ़ने में सक्षम होना चाहिए। बड़े बैच के लिए अधिक मेमोरी चाहिए।', 'चित्र आपके ब्राउज़र में प्रोसेस होते हैं, सर्वर पर अपलोड नहीं होते। पारदर्शिता सफेद बनती है। चित्रों का अनुपात नहीं बदलता और उन्हें काटा नहीं जाता। PDF में OCR या खोजने योग्य टेक्स्ट नहीं जोड़ा जाता।', 'असाइनमेंट के लिए PDF', 'असाइनमेंट की तस्वीरें सही क्रम में रखें और उलटे पृष्ठ घुमाएँ। छोटी फ़ाइल के लिए कॉम्पैक्ट गुणवत्ता चुनें। जमा करने से पहले PDF खोलकर हर पृष्ठ और पोर्टल की फ़ाइल सीमा जाँचें। किसी पोर्टल पर स्वीकृति की गारंटी नहीं है।'],
  de: ['So wandelst du Bilder in PDF um', 'Wähle JPG, PNG, WebP, GIF, BMP oder AVIF. Halte auf dem Handy ein Vorschaubild kurz gedrückt und ziehe es an die gewünschte Position. Alternativ kannst du die Pfeiltasten verwenden.', 'Wähle A4, US Letter oder An Bild anpassen. Standardmäßig sind keine Ränder eingestellt. PDF herunterladen erstellt die Datei und startet den Download.', 'Grenzen und Bildqualität', 'Bis zu 60 Bilder, 25 MB je Bild, 150 MB insgesamt und 40 Megapixel je Bild. Das Format muss vom Browser unterstützt werden. Große Stapel benötigen mehr Arbeitsspeicher.', 'Die Verarbeitung erfolgt im Browser ohne Upload der Bilder. Transparenz wird weiß. Bilder werden weder beschnitten noch verzerrt. Es gibt keine OCR; Text in Bildern wird nicht durchsuchbar.', 'Dokumente auf A4 vorbereiten', 'Wähle A4 für Dokumente zum Drucken. Drehe quer liegende Seiten und prüfe die PDF vor dem Druck. Unterschiedliche Seitenverhältnisse können auch ohne Ränder weiße Flächen erzeugen. An Bild anpassen folgt dem Bildformat.'],
  fr: ['Comment convertir des images en PDF', 'Choisissez des JPG, PNG, WebP, GIF, BMP ou AVIF. Sur mobile, maintenez brièvement un aperçu puis faites-le glisser. Les boutons fléchés permettent aussi de modifier l’ordre.', 'Choisissez A4, US Letter ou Adapter à l’image. Les marges sont désactivées par défaut. Télécharger le PDF crée le fichier puis lance le téléchargement.', 'Limites et qualité', 'Jusqu’à 60 images, 25 Mo par image, 150 Mo au total et 40 mégapixels par image. Votre navigateur doit pouvoir décoder le format. Les grands lots nécessitent davantage de mémoire.', 'Les images sont traitées dans le navigateur sans envoi à un serveur. La transparence devient blanche. Les proportions sont conservées sans recadrage. Aucun OCR : le texte des images ne devient pas consultable par recherche.', 'Préparer un document A4', 'Choisissez A4 pour un document à imprimer. Faites pivoter les pages et vérifiez le PDF avant impression. Des proportions différentes peuvent laisser du blanc même sans marges. Adapter à l’image suit les dimensions de chaque image.'],
  es: ['Cómo convertir imágenes a PDF', 'Elige JPG, PNG, WebP, GIF, BMP o AVIF. En el móvil, mantén pulsada brevemente una vista previa y arrástrala. También puedes usar los botones de flecha.', 'Elige A4, US Letter o Ajustar a la imagen. No hay márgenes de forma predeterminada. Descargar PDF crea el archivo e inicia la descarga.', 'Límites y calidad', 'Hasta 60 imágenes, 25 MB por imagen, 150 MB en total y 40 megapíxeles por imagen. Tu navegador debe poder decodificar el formato. Los lotes grandes necesitan más memoria.', 'Las imágenes se procesan en el navegador sin subirlas a un servidor. La transparencia se vuelve blanca. No se recortan ni deforman las imágenes. No hay OCR: el texto de las imágenes no se convierte en texto que puedas buscar.', 'Preparar documentos para imprimir', 'Selecciona A4 o US Letter según el papel de tu impresora. Gira las páginas y comprueba el PDF antes de imprimir. Las proporciones distintas pueden dejar espacios blancos incluso sin márgenes. Ajustar a la imagen sigue el tamaño de cada imagen.'],
} as const

export default function LocalizedGuide({ locale }: { locale: Exclude<Locale, 'en'> }) {
  const t = translator(locale), content = guides[locale]
  const faq = {
    hi: ['सामान्य प्रश्न', 'क्या मेरी फ़ाइलें अपलोड होती हैं?', 'नहीं। चित्र आपके ब्राउज़र में प्रोसेस होते हैं। वेबसाइट अपने कोड और फ़ॉन्ट जैसी फ़ाइलों के लिए सामान्य नेटवर्क अनुरोध करती है।', 'क्या PDF का पाठ खोजा जा सकता है?', 'नहीं। हर चित्र एक PDF पृष्ठ बनता है। यह टूल OCR नहीं करता है।'],
    de: ['Häufige Fragen', 'Werden meine Dateien hochgeladen?', 'Nein. Bilder werden in deinem Browser verarbeitet. Die Website lädt ihren Code und ihre Schriftarten über normale Netzwerkanfragen.', 'Ist der Text in der PDF durchsuchbar?', 'Nein. Jedes Bild wird zu einer PDF-Seite. Dieses Werkzeug führt keine Texterkennung (OCR) durch.'],
    fr: ['Questions fréquentes', 'Mes fichiers sont-ils envoyés à un serveur ?', 'Non. Les images sont traitées dans votre navigateur. Le site effectue des requêtes normales pour charger son code et ses polices.', 'Le texte du PDF est-il consultable par recherche ?', 'Non. Chaque image devient une page PDF. Cet outil ne réalise pas de reconnaissance de texte (OCR).'],
    es: ['Preguntas frecuentes', '¿Se suben mis archivos a un servidor?', 'No. Las imágenes se procesan en tu navegador. El sitio realiza solicitudes normales para cargar su código y sus fuentes.', '¿Se puede buscar el texto del PDF?', 'No. Cada imagen se convierte en una página PDF. Esta herramienta no realiza reconocimiento de texto (OCR).'],
  }[locale]
  return <section className="pdf-guide" aria-labelledby="pdf-guide-title">
    <nav aria-label="Breadcrumb"><a href="/">Bloomollo</a> / {t('Image to PDF')}</nav>
    <header><h2 id="pdf-guide-title">{t('Image to PDF')}</h2><p>{localeMetadata[locale].description}</p><a href="#main-content">{t('Image to PDF')} ↑</a></header>
    <div className="pdf-guide-columns"><article><h2>{content[0]}</h2><p>{content[1]}</p><p>{content[2]}</p></article><article><h2>{content[3]}</h2><p>{content[4]}</p><p>{content[5]}</p></article></div>
    <article><h2>{content[6]}</h2><p>{content[7]}</p></article>
    <section className="pdf-guide-faq" aria-labelledby="localized-faq-title"><h2 id="localized-faq-title">{faq[0]}</h2><details><summary>{faq[1]}</summary><p>{faq[2]}</p></details><details><summary>{faq[3]}</summary><p>{faq[4]}</p></details></section>
  </section>
}