import assert from 'node:assert/strict'
import { readFile, access } from 'node:fs/promises'
const slugs = ['debug2ai', 'draft-rescue', 'page-capture', 'page-ink', 'video-speed-booster', 'sound-booster']
const home = await readFile(new URL('../dist/index.html', import.meta.url), 'utf8')
assert.equal((home.match(/class="product-card"/g) || []).length, 6)
assert.equal((home.match(/<h1\b/g) || []).length, 1)
assert.match(home, /Browse Chrome Extensions/)
assert.ok(!home.includes('Save the words.'))
assert.match(home, /href="\/tools\/image-to-pdf\/"/)
const converter = await readFile(new URL('../dist/tools/image-to-pdf/index.html', import.meta.url), 'utf8')
assert.match(converter, /Image to PDF/)
assert.match(converter, /Files stay on your device/)
assert.match(converter, /PDF settings/)
assert.equal((converter.match(/<h1\b/g) || []).length, 1)
for (const slug of slugs) {
  const html = await readFile(new URL(`../dist/extensions/${slug}/index.html`, import.meta.url), 'utf8')
  assert.equal((html.match(/<h1\b/g) || []).length, 1, `${slug}: single h1`)
  assert.match(html, /name="description"/)
  assert.match(html, /application\/ld\+json/)
  assert.match(html, /Limitations/)
  assert.match(html, /<h2>What it does<\/h2>/)
  assert.match(html, /<h2>How to use<\/h2>/)
  assert.ok(!html.includes('The context that matters'))
  assert.match(html, /disabled=""/)
  assert.ok(!html.includes('href="#"'), `${slug}: no dead placeholder links`)
  assert.ok(!html.includes('vite.svg'))
  const schema = JSON.parse(html.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1])
  assert.equal(schema['@type'], 'SoftwareApplication')
  assert.ok(!schema.aggregateRating, 'No fabricated ratings')
}
await access(new URL('../dist/fonts/manrope-latin.woff2', import.meta.url))
await access(new URL('../dist/fonts/OFL.txt', import.meta.url))
await access(new URL('../dist/404.html', import.meta.url))
const worker = await readFile(new URL('../dist/sw.js', import.meta.url), 'utf8')
assert.match(worker, /bloomollo-assets-/)
assert.match(worker, /woff2/)
assert.match(worker, /event.request.mode === 'navigate'/)
console.log('PASS: six cards, six prerendered product pages, metadata, structured data, unavailable store state, font/license assets, and 404 page.')