import assert from 'node:assert/strict'
import { readFile, access } from 'node:fs/promises'
const slugs = ['debug2ai', 'draft-rescue', 'page-capture', 'page-ink', 'video-speed-booster', 'sound-booster']
const home = await readFile(new URL('../dist/index.html', import.meta.url), 'utf8')
assert.match(home, /<title>Bloomollo - A small upgrade\. A better everyday\.<\/title>/)
assert.match(home, /web utility tools, Chrome extensions and an image-to-PDF converter/)
assert.ok(!home.includes('Six focused Chrome extensions'))
const homeSchema = JSON.parse(home.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1])
const website = homeSchema['@graph'].find(node => node['@type'] === 'WebSite')
assert.equal(website.name, 'Bloomollo')
assert.equal(website.alternateName, 'bloomollo.dpdns.org')
assert.equal(website.url, 'https://bloomollo.dpdns.org/')
assert.match(home, /rel="icon" type="image\/png" sizes="96x96" href="\/favicon-96.png"/)
for (const [file, size] of [['favicon-96.png', 96], ['apple-touch-icon.png', 180]]) {
  const bytes = await readFile(new URL(`../dist/${file}`, import.meta.url))
  assert.equal(bytes.subarray(1, 4).toString(), 'PNG')
  assert.equal(bytes.readUInt32BE(16), size)
  assert.equal(bytes.readUInt32BE(20), size)
}
assert.equal((home.match(/class="product-card"/g) || []).length, 6)
assert.equal((home.match(/<h1\b/g) || []).length, 1)
assert.match(home, /Browse Chrome Extensions/)
assert.ok(!home.includes('Save the words.'))
assert.match(home, /href="\/tools\/image-to-pdf\/"/)
const converter = await readFile(new URL('../dist/tools/image-to-pdf/index.html', import.meta.url), 'utf8')
assert.match(converter, /Image to PDF/)
assert.match(converter, /Files stay on your device/)
assert.match(converter, /PDF settings/)
assert.equal((converter.match(/<h1\b/g) || []).length, 1)
assert.match(converter, /legal-footer--tool/)
assert.match(converter, /brand-trademark/)
const canonical = 'https://bloomollo.dpdns.org/tools/image-to-pdf/'
assert.ok(converter.includes(`<link rel="canonical" href="${canonical}"/>`))
assert.match(converter, /JPG to PDF Converter/)
assert.match(converter, /How to convert JPG to PDF/)
assert.match(converter, /Does this converter make text searchable/)
assert.match(converter, /name="robots" content="index,follow/)
const toolSchema = JSON.parse(converter.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1])
assert.equal(toolSchema.url, canonical)
assert.equal(toolSchema['@type'], 'WebApplication')
assert.equal(toolSchema.offers.price, '0')
assert.ok(!toolSchema.aggregateRating, 'No fabricated converter ratings')
const sitemap = await readFile(new URL('../dist/sitemap.xml', import.meta.url), 'utf8')
assert.ok(sitemap.includes(`<loc>${canonical}</loc>`))
assert.ok(!sitemap.includes('/404/'))
const robots = await readFile(new URL('../dist/robots.txt', import.meta.url), 'utf8')
assert.match(robots, /Sitemap: https:\/\/bloomollo\.dpdns\.org\/sitemap\.xml/)
const notFound = await readFile(new URL('../dist/404.html', import.meta.url), 'utf8')
assert.match(notFound, /name="robots" content="noindex"/)
assert.ok(!notFound.includes('rel="canonical"'))
for (const html of [home, converter]) {
  assert.match(html, /href="\/terms\/"/)
  assert.match(html, /href="\/privacy\/"/)
  assert.match(html, /All rights reserved/)
}
const terms = await readFile(new URL('../dist/terms/index.html', import.meta.url), 'utf8')
assert.match(terms, /Terms of Service/)
assert.match(terms, /Using Bloomollo/)
for (const slug of slugs) {
  const html = await readFile(new URL(`../dist/extensions/${slug}/index.html`, import.meta.url), 'utf8')
  assert.equal((html.match(/<h1\b/g) || []).length, 1, `${slug}: single h1`)
  assert.match(html, /name="description"/)
  assert.match(html, /application\/ld\+json/)
  assert.match(html, /Limitations/)
  assert.match(html, /<h2>What it does<\/h2>/)
  assert.match(html, /<h2>How to use<\/h2>/)
  assert.ok(!html.includes('The context that matters'))
  assert.match(html, /disabled=""/)
  assert.ok(!html.includes('href="#"'), `${slug}: no dead placeholder links`)
  assert.ok(!html.includes('vite.svg'))
  const schema = JSON.parse(html.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1])
  assert.equal(schema['@type'], 'SoftwareApplication')
  assert.ok(!schema.aggregateRating, 'No fabricated ratings')
}
await access(new URL('../dist/fonts/manrope-latin.woff2', import.meta.url))
await access(new URL('../dist/fonts/OFL.txt', import.meta.url))
await access(new URL('../dist/404.html', import.meta.url))
const worker = await readFile(new URL('../dist/sw.js', import.meta.url), 'utf8')
assert.match(worker, /bloomollo-assets-/)
assert.match(worker, /woff2/)
assert.match(worker, /event.request.mode === 'navigate'/)
console.log('PASS: six cards, six prerendered product pages, metadata, structured data, unavailable store state, font/license assets, and 404 page.')