import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
const targets = await (await fetch('http://127.0.0.1:9333/json')).json()
const target = targets.find(t => t.type === 'page')
if (!target) throw new Error('Start a Chromium browser with --remote-debugging-port=9333 first.')
const ws = new WebSocket(target.webSocketDebuggerUrl)
await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }))
let id = 0
const pending = new Map()
const errors = []
ws.addEventListener('message', event => {
  const message = JSON.parse(event.data)
  if (message.method === 'Runtime.exceptionThrown') errors.push(message.params.exceptionDetails)
  if (message.method === 'Runtime.consoleAPICalled' && message.params.type === 'error') errors.push(message.params.args)
  if (message.id) {
    const callback = pending.get(message.id)
    if (callback) { pending.delete(message.id); message.error ? callback.reject(message.error) : callback.resolve(message.result) }
  }
})
function send(method, params = {}) {
  return new Promise((resolve, reject) => { const n = ++id; pending.set(n, { resolve, reject }); ws.send(JSON.stringify({ id: n, method, params })) })
}
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
async function evaluate(expression) {
  const result = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true })
  if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails))
  return result.result.value
}
await send('Runtime.enable'); await send('Page.enable')
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
await send('Page.navigate', { url: 'http://127.0.0.1:4173/' }); await sleep(1600)
assert.equal(await evaluate('document.querySelectorAll(".product-card").length'), 6)
assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true)
assert.equal(await evaluate('document.fonts.check("14px Manrope")'), true)
await evaluate('document.querySelector("#extensions").scrollIntoView({behavior:"instant"})'); await sleep(1000)
await evaluate('[...document.querySelectorAll(".filter-row button")].find(b=>b.textContent==="Media").click()'); await sleep(350)
assert.equal(await evaluate('document.querySelectorAll(".product-card").length'), 2)
await evaluate('document.querySelector(".filter-row button").click()'); await sleep(1000)
const output = new URL('../checks/', import.meta.url)
await mkdir(output, { recursive: true })
async function screenshot(name) {
  const shot = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false })
  await writeFile(new URL(name, output), Buffer.from(shot.data, 'base64'))
}
await screenshot('collection-desktop.png')
await evaluate('scrollTo({top:0,behavior:"instant"})'); await sleep(500)
assert.equal(await evaluate('document.querySelector(".cube")'), null)
assert.equal(await evaluate('document.querySelectorAll(".rotating-logo-cube .logo-face").length'), 6)
assert.equal(await evaluate('document.querySelector(".hero").textContent.includes("Less friction. More flow.")'), false)
const logoBefore = await evaluate('getComputedStyle(document.querySelector(".rotating-logo-cube")).transform')
await sleep(180)
assert.notEqual(await evaluate('getComputedStyle(document.querySelector(".rotating-logo-cube")).transform'), logoBefore, 'Brand cube rotates automatically')
await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
assert.equal(await evaluate('getComputedStyle(document.querySelector(".rotating-logo-cube")).animationName'), 'none')
await send('Emulation.setEmulatedMedia', { features: [] })
assert.equal(await evaluate('document.querySelectorAll(".corner-glare").length'), 2)
assert.equal(await evaluate('document.querySelectorAll(".floor-tile").length'), 216)
assert.equal(await evaluate('document.querySelectorAll(".large-asterisk .brand-mark,.closing-star .brand-mark").length'), 2)
const tilePoint = await evaluate('(()=>{for(let y=innerHeight-130;y>innerHeight-400;y-=12){for(let x=200;x<innerWidth-200;x+=30){const e=document.elementFromPoint(x,y);if(e?.classList.contains("floor-tile")){e.dataset.testTile="true";return {x,y}}}}return null})()')
assert.ok(tilePoint, `Perspective floor must be reachable by the pointer: ${await evaluate('JSON.stringify({floor:document.querySelector(".interactive-floor").getBoundingClientRect().toJSON(),hits:[650,700,750,800,850].map(y=>[y,document.elementFromPoint(500,y)?.className])})')}`)
await send('Input.dispatchMouseEvent', { type: 'mouseMoved', ...tilePoint }); await sleep(200)
assert.ok(await evaluate('Number(getComputedStyle(document.querySelector("[data-test-tile]"),"::after").opacity) > .9'))
await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 50, y: 140 }); await sleep(60)
assert.ok(await evaluate('Number(getComputedStyle(document.querySelector("[data-test-tile]"),"::after").opacity) > .8'), 'Tile retains light briefly after pointer leaves')
await sleep(1200)
assert.ok(await evaluate('Number(getComputedStyle(document.querySelector("[data-test-tile]"),"::after").opacity) < .05'), 'Tile fades out')
await screenshot('hero-desktop.png')
await evaluate('document.querySelector(".globe-section").scrollIntoView({behavior:"instant"})'); await sleep(800)
const canvasBounds = await evaluate('(()=>{const b=document.querySelector("canvas").getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2}})()')
const globeBefore = await evaluate('document.querySelector("canvas").toDataURL()')
assert.equal(await evaluate('Number(document.querySelector("canvas").dataset.particleCount)'), 9500)
await send('Input.dispatchMouseEvent', { type: 'mouseMoved', ...canvasBounds }); await sleep(400)
await send('Input.dispatchMouseEvent', { type: 'mousePressed', button: 'left', clickCount: 1, ...canvasBounds })
await sleep(20)
await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: canvasBounds.x + 40, y: canvasBounds.y + 5, button: 'left', buttons: 1 })
await sleep(20)
await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: canvasBounds.x + 80, y: canvasBounds.y + 10, button: 'left', buttons: 1 })
await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: canvasBounds.x + 80, y: canvasBounds.y + 10, button: 'left', clickCount: 1 })
await sleep(60)
const momentum = await evaluate('Number(document.querySelector("canvas").dataset.momentum)')
const releasedRotation = await evaluate('Number(document.querySelector("canvas").dataset.rotation)')
assert.ok(momentum > .0001, 'Drag release retains angular velocity')
await sleep(300)
const laterMomentum = await evaluate('Number(document.querySelector("canvas").dataset.momentum)')
assert.ok(laterMomentum > 0 && laterMomentum < momentum, 'Inertia decays rather than stopping instantly')
assert.ok(await evaluate('Number(document.querySelector("canvas").dataset.rotation)') - releasedRotation > .05, 'Globe coasts after release')
assert.notEqual(await evaluate('document.querySelector("canvas").toDataURL()'), globeBefore)
await evaluate('document.querySelector(".globe-controls button").click()')
assert.equal(await evaluate('document.querySelector(".globe-controls button").getAttribute("aria-pressed")'), 'true')
await screenshot('globe-desktop.png')
for (const slug of ['debug2ai', 'draft-rescue', 'page-capture', 'page-ink', 'video-speed-booster', 'sound-booster']) {
  await send('Page.navigate', { url: `http://127.0.0.1:4173/extensions/${slug}/` }); await sleep(550)
  assert.equal(await evaluate('document.querySelectorAll("h1").length'), 1)
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true)
  assert.equal(await evaluate('document.querySelectorAll(".store-pending button:disabled").length'), 2)
}
await screenshot('product-desktop.png')
await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
await send('Page.navigate', { url: 'http://127.0.0.1:4173/' }); await sleep(1000)
assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true)
await screenshot('hero-mobile.png')
await evaluate('document.querySelector(".menu-toggle").click()'); await sleep(400)
assert.equal(await evaluate('document.querySelector(".menu-toggle").getAttribute("aria-expanded")'), 'true')
await evaluate('document.querySelector(".mobile-nav a").click()'); await sleep(1000)
assert.equal(await evaluate('document.querySelector(".menu-toggle").getAttribute("aria-expanded")'), 'false')
await screenshot('collection-mobile.png')
await evaluate('document.querySelector("#faq").scrollIntoView({behavior:"instant"});document.querySelector(".faq-list summary").click()'); await sleep(350)
assert.equal(await evaluate('document.querySelector(".faq-list details").open'), true)
await send('Page.navigate', { url: 'http://127.0.0.1:4173/extensions/draft-rescue/' }); await sleep(750)
assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true)
await screenshot('product-mobile.png')
assert.equal(errors.length, 0, `Browser errors: ${JSON.stringify(errors)}`)
console.log('PASS: desktop/mobile layout, filters, removed subtitle, rotating brand cube and reduced motion, corner glare, cube branding, real floor hover/delayed fade, dense globe and decaying drag inertia, six product routes, mobile menu, FAQs, fonts, and no browser/hydration errors.')
ws.close()